Marsmodel: pertesuv Module Reference
pertesuv Module Reference
Lire le contenu des fichiers sources et les stocker dans des tableaux dans le programme.
Public Member Functions
subroutine showuv
subroutine showuvdestroyed
subroutine conversion_b (destroyed)
Public Attributes
real fmars
real glycine_destroyed_per_photon
real gdest
Detailed Description
Lire le contenu des fichiers sources et les stocker dans des tableaux dans le programme.
Author
LAHIYANE Atik
Definition at line 15 of file Pertes.f90.
Member Function/Subroutine Documentation
subroutine pertesuv::conversion_b (real destroyed)
Definition at line 42 of file Pertes.f90.
Referenced by controlleur::application_pert().
subroutine pertesuv::showuv ()
Definition at line 22 of file Pertes.f90.
References showuvdestroyed().
subroutine pertesuv::showuvdestroyed ()
Definition at line 38 of file Pertes.f90.
Referenced by controlleur::application_pert(), and showuv().
Member Data Documentation
real pertesuv::fmars
Definition at line 18 of file Pertes.f90.
real pertesuv::gdest
Definition at line 20 of file Pertes.f90.
real pertesuv::glycine_destroyed_per_photon
Definition at line 19 of file Pertes.f90.
The documentation for this module was generated from the following file:
Pertes.f90