Marsmodel: pertes Module Reference
pertes Module Reference
Public Member Functions
function emitted_solar (lamb)
real function calcul_z (lat, t)
real function emitted_solar_on_top_of_atmosphere (lat, lamb)
real function flux_surface (lat, lamb, density, absorp)
Public Attributes
real, parameter t =5780
real, parameter omega =7e-10
real, parameter d =2.27e8
real, parameter pi =3.141
real, parameter p =88775
real, parameter rsm =2.27e8
Detailed Description
Definition at line 1 of file Pert.f90.
Member Function/Subroutine Documentation
real function pertes::calcul_z (real lat, real t)
Definition at line 25 of file Pert.f90.
Referenced by emitted_solar_on_top_of_atmosphere().
function pertes::emitted_solar (real lamb)
Definition at line 16 of file Pert.f90.
Referenced by emitted_solar_on_top_of_atmosphere().
real function pertes::emitted_solar_on_top_of_atmosphere (real lat, real lamb)
Definition at line 35 of file Pert.f90.
References calcul_z(), and emitted_solar().
Referenced by flux_surface().
real function pertes::flux_surface (real lat, real lamb, real density, real absorp)
Definition at line 44 of file Pert.f90.
References emitted_solar_on_top_of_atmosphere().
Member Data Documentation
real, parameter pertes::d =2.27e8
Definition at line 8 of file Pert.f90.
real, parameter pertes::omega =7e-10
Definition at line 7 of file Pert.f90.
real, parameter pertes::p =88775
Definition at line 10 of file Pert.f90.
real, parameter pertes::pi =3.141
Definition at line 9 of file Pert.f90.
real, parameter pertes::rsm =2.27e8
Definition at line 11 of file Pert.f90.
real, parameter pertes::t =5780
Definition at line 6 of file Pert.f90.
The documentation for this module was generated from the following file:
Pert.f90