Marsmodel: gnufor2 Module Reference
gnufor2 Module Reference
Data Types
interface image
interface plot
interface surf
Public Member Functions
character(len=33) function my_date_and_time ()
character(len=nc) function output_terminal (terminal)
subroutine image_4 (x, y, rgb, pause, terminal, filename, persist, input)
subroutine image_3 (rgb, pause, terminal, filename, persist, input)
subroutine image_2 (x, y, gray, pause, palette, terminal, filename, persist, input)
subroutine image_1 (gray, pause, palette, terminal, filename, persist, input)
subroutine plot3d (x, y, z, pause, color, terminal, filename, persist, input, linewidth)
subroutine hist (x, n, pause, color, terminal, filename, persist, input)
subroutine surf_3 (x, y, z, pause, palette, terminal, filename, pm3d, contour, persist, input)
subroutine surf_2 (z, pause, palette, terminal, filename, pm3d, contour, persist, input)
subroutine surf_1 (xyz, pause, palette, terminal, filename, pm3d, contour, persist, input)
subroutine plot_4 (x1, y1, x2, y2, x3, y3, x4, y4, style, pause, color1, color2, color3, color4, terminal, filename, polar, persist, input, linewidth)
subroutine plot_3 (x1, y1, x2, y2, x3, y3, style, pause, color1, color2, color3, terminal, filename, polar, persist, input, linewidth)
subroutine plot_2 (x1, y1, x2, y2, style, pause, color1, color2, terminal, filename, polar, persist, input, linewidth)
subroutine plot_1 (x1, y1, style, pause, color1, terminal, filename, polar, persist, input, linewidth)
subroutine run_gnuplot (command_file_name)
subroutine get_unit (iunit)
Public Attributes
character(len=3), parameter default_linewidth ='1'
character(len=100), parameter default_color1 ='blue'
character(len=100), parameter default_color2 ='dark-green'
character(len=100), parameter default_color3 ='orange-red'
character(len=100), parameter default_color4 ='dark-salmon'
character(len=100), parameter default_terminal ='wxt'
character(len=100), parameter default_palette ='CMY'
Detailed Description
Definition at line 18 of file mygnu.f90.
Member Function/Subroutine Documentation
subroutine gnufor2::get_unit (integer iunit)
Definition at line 1747 of file mygnu.f90.
Referenced by hist(), image_1(), image_2(), image_3(), image_4(), plot3d(), plot_1(), plot_2(), plot_3(), plot_4(), and surf_1().
subroutine gnufor2::hist (real(kind=8), dimension(:), intent(in) x, integer, intent(in) n, real(kind=4), optional pause, character(len=*), optional color, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional persist, character(len=*), optional input)
Definition at line 692 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::image_1 (real(kind=4), dimension(:,:), intent(in) gray, real(kind=4), optional pause, character(len=*), optional palette, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional persist, character(len=*), optional input)
Definition at line 461 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::image_2 (real(kind=4), dimension(:), intent(in) x, real(kind=4), dimension(:), intent(in) y, real(kind=4), dimension(:,:), intent(in) gray, real(kind=4), optional pause, character(len=*), optional palette, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional persist, character(len=*), optional input)
Definition at line 334 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::image_3 (integer, dimension(:,:,:), intent(in) rgb, real(kind=4), optional pause, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional persist, character(len=*), optional input)
Definition at line 218 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::image_4 (real(kind=4), dimension(:), intent(in) x, real(kind=4), dimension(:), intent(in) y, integer, dimension(:,:,:), intent(in) rgb, real(kind=4), optional pause, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional persist, character(len=*), optional input)
Definition at line 92 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
character(len=33) function gnufor2::my_date_and_time ()
Definition at line 57 of file mygnu.f90.
Referenced by hist(), image_1(), image_2(), image_3(), image_4(), plot3d(), plot_1(), plot_2(), plot_3(), plot_4(), and surf_1().
character(len=nc) function gnufor2::output_terminal (character(len=*), intent(in) terminal)
Definition at line 74 of file mygnu.f90.
Referenced by hist(), image_1(), image_2(), image_3(), image_4(), plot3d(), plot_1(), plot_2(), plot_3(), plot_4(), and surf_1().
subroutine gnufor2::plot3d (real(kind=8), dimension(:), intent(in) x, real(kind=8), dimension(:), intent(in) y, real(kind=8), dimension(:), intent(in) z, real(kind=4), optional pause, character(len=*), optional color, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional persist, character(len=*), optional input, real(kind=4), optional linewidth)
Definition at line 579 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::plot_1 (real(kind=8), dimension(:), intent(in) x1, real(kind=8), dimension(:), intent(in) y1, character(len=*), optional style, real(kind=4), optional pause, character(len=*), optional color1, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional polar, character(len=*), optional persist, character(len=*), optional input, real(kind=4), optional linewidth)
Definition at line 1579 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::plot_2 (real(kind=8), dimension(:), intent(in) x1, real(kind=8), dimension(:), intent(in) y1, real(kind=8), dimension(:), intent(in) x2, real(kind=8), dimension(:), intent(in) y2, character(len=*), optional style, real(kind=4), optional pause, character(len=*), optional color1, character(len=*), optional color2, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional polar, character(len=*), optional persist, character(len=*), optional input, real(kind=4), optional linewidth)
Definition at line 1413 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::plot_3 (real(kind=8), dimension(:), intent(in) x1, real(kind=8), dimension(:), intent(in) y1, real(kind=8), dimension(:), intent(in) x2, real(kind=8), dimension(:), intent(in) y2, real(kind=8), dimension(:), intent(in) x3, real(kind=8), dimension(:), intent(in) y3, character(len=*), optional style, real(kind=4), optional pause, character(len=*), optional color1, character(len=*), optional color2, character(len=*), optional color3, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional polar, character(len=*), optional persist, character(len=*), optional input, real(kind=4), optional linewidth)
Definition at line 1225 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::plot_4 (real(kind=8), dimension(:), intent(in) x1, real(kind=8), dimension(:), intent(in) y1, real(kind=8), dimension(:), intent(in) x2, real(kind=8), dimension(:), intent(in) y2, real(kind=8), dimension(:), intent(in) x3, real(kind=8), dimension(:), intent(in) y3, real(kind=8), dimension(:), intent(in) x4, real(kind=8), dimension(:), intent(in) y4, character(len=*), optional style, real(kind=4), optional pause, character(len=*), optional color1, character(len=*), optional color2, character(len=*), optional color3, character(len=*), optional color4, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional polar, character(len=*), optional persist, character(len=*), optional input, real(kind=4), optional linewidth)
Definition at line 1016 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::run_gnuplot (character (len = *) command_file_name)
Definition at line 1724 of file mygnu.f90.
Referenced by hist(), image_1(), image_2(), image_3(), image_4(), plot3d(), plot_1(), plot_2(), plot_3(), plot_4(), and surf_1().
subroutine gnufor2::surf_1 (real(kind=8), dimension(:,:,:), intent(in) xyz, real(kind=4), optional pause, character(len=*), optional palette, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional pm3d, character(len=*), optional contour, character(len=*), optional persist, character(len=*), optional input)
Definition at line 884 of file mygnu.f90.
References get_unit(), my_date_and_time(), output_terminal(), and run_gnuplot().
subroutine gnufor2::surf_2 (real(kind=8), dimension(:,:), intent(in) z, real(kind=4), optional pause, character(len=*), optional palette, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional pm3d, character(len=*), optional contour, character(len=*), optional persist, character(len=*), optional input)
Definition at line 856 of file mygnu.f90.
References gnufor2::surf::surf_1().
subroutine gnufor2::surf_3 (real(kind=8), dimension(:), intent(in) x, real(kind=8), dimension(:), intent(in) y, real(kind=8), dimension(:,:), intent(in) z, real(kind=4), optional pause, character(len=*), optional palette, character(len=*), optional terminal, character(len=*), optional filename, character(len=*), optional pm3d, character(len=*), optional contour, character(len=*), optional persist, character(len=*), optional input)
Definition at line 823 of file mygnu.f90.
References gnufor2::surf::surf_1().
Member Data Documentation
character(len=100), parameter gnufor2::default_color1 ='blue'
Definition at line 24 of file mygnu.f90.
character(len=100), parameter gnufor2::default_color2 ='dark-green'
Definition at line 25 of file mygnu.f90.
character(len=100), parameter gnufor2::default_color3 ='orange-red'
Definition at line 26 of file mygnu.f90.
character(len=100), parameter gnufor2::default_color4 ='dark-salmon'
Definition at line 27 of file mygnu.f90.
character(len=3), parameter gnufor2::default_linewidth ='1'
Definition at line 23 of file mygnu.f90.
character(len=100), parameter gnufor2::default_palette ='CMY'
Definition at line 29 of file mygnu.f90.
character(len=100), parameter gnufor2::default_terminal ='wxt'
Definition at line 28 of file mygnu.f90.
The documentation for this module was generated from the following file:
mygnu.f90