Marsmodel: readfromfile Module Reference
readfromfile Module Reference
Lire le contenu des fichiers sources et les stocker dans des tableaux dans le programme.
Public Member Functions
subroutine filetoarray
Récupére les valeurs du flux UV à partir du fichier de Patel.
subroutine extraire_colonne (lat_titude)
Utilise le paramètre 'lat_titude' et extrait du fichier chargé par FileToarray la colonne des valeur du flux UV correspondante à la latitude choisie.
integer function hash (la_titude)
!Fonction qui récupére une latitude et renvoie l'indice de la colonne de valeurs (dans le fichier de Patel)
real function diminution_uv_profondeur (z, Fuv)
Public Attributes
integer, dimension(200) landa
real, dimension(200) tab
integer ierror
integer ierror1
integer i
integer indicateur
integer, dimension(34) latitude
real, dimension(200, 34) marsuv
Detailed Description
Lire le contenu des fichiers sources et les stocker dans des tableaux dans le programme.
Author
LAHIYANE Atik
Definition at line 15 of file readFromFile.f90.
Member Function/Subroutine Documentation
real function readfromfile::diminution_uv_profondeur (integer z, real Fuv)
Definition at line 96 of file readFromFile.f90.
Referenced by controlleur::diminution_general().
subroutine readfromfile::extraire_colonne (integer lat_titude)
Utilise le paramètre 'lat_titude' et extrait du fichier chargé par FileToarray la colonne des valeur du flux UV correspondante à la latitude choisie.
Author
LAHIYANE Atik
Definition at line 62 of file readFromFile.f90.
References hash().
Referenced by controlleur::uv_integrale().
subroutine readfromfile::filetoarray ()
Récupére les valeurs du flux UV à partir du fichier de Patel.
Author
LAHIYANE Atik
Definition at line 34 of file readFromFile.f90.
Referenced by controlleur::run().
integer function readfromfile::hash (integer la_titude)
!Fonction qui récupére une latitude et renvoie l'indice de la colonne de valeurs (dans le fichier de Patel)
Author
LAHIYANE Atik
Definition at line 81 of file readFromFile.f90.
Referenced by extraire_colonne().
Member Data Documentation
integer readfromfile::i
Definition at line 19 of file readFromFile.f90.
integer readfromfile::ierror
Definition at line 18 of file readFromFile.f90.
integer readfromfile::ierror1
Definition at line 18 of file readFromFile.f90.
integer readfromfile::indicateur
Definition at line 20 of file readFromFile.f90.
integer, dimension(200) readfromfile::landa
Definition at line 16 of file readFromFile.f90.
integer, dimension(34) readfromfile::latitude
Definition at line 21 of file readFromFile.f90.
real, dimension(200,34) readfromfile::marsuv
Definition at line 22 of file readFromFile.f90.
real, dimension(200) readfromfile::tab
Definition at line 17 of file readFromFile.f90.
The documentation for this module was generated from the following file:
readFromFile.f90