Marsmodel: sources Module Reference
sources Module Reference
Lire le contenu des fichiers sources et les stocker dans des tableaux dans le programme.
Public Member Functions
subroutine show_values
subroutine gly
subroutine pa
subroutine research (s)
Public Attributes
real, parameter fmic_met =7.08
real, parameter glycine =0.25
real fgly
real pah
real, parameter density =2
Detailed Description
Lire le contenu des fichiers sources et les stocker dans des tableaux dans le programme.
Author
LAHIYANE Atik
Definition at line 16 of file sources.f90.
Member Function/Subroutine Documentation
subroutine sources::gly ()
Definition at line 35 of file sources.f90.
Referenced by research().
subroutine sources::pa ()
Definition at line 50 of file sources.f90.
Referenced by research().
subroutine sources::research (character(len=20) s)
Definition at line 65 of file sources.f90.
References gly(), and pa().
Referenced by controlleur::run().
subroutine sources::show_values ()
Definition at line 25 of file sources.f90.
Referenced by controlleur::run().
Member Data Documentation
real, parameter sources::density =2
Definition at line 22 of file sources.f90.
real sources::fgly
Definition at line 20 of file sources.f90.
real, parameter sources::fmic_met =7.08
Definition at line 18 of file sources.f90.
real, parameter sources::glycine =0.25
Definition at line 19 of file sources.f90.
real sources::pah
Definition at line 21 of file sources.f90.
The documentation for this module was generated from the following file:
sources.f90