Marsmodel: controlleur Module Reference
controlleur Module Reference
Ce module contient toutes les méthodes qui font les traitements des données.
Public Member Functions
subroutine bilan (name)
Fait le bilan (sources-pertes) en prenant comme paramètre d'entrée le nom de la molécule choisi par l'utilisateur.
subroutine application_pert (name)
Demande à l'utilisateur d'entrée une latitude, un intervalle de longeur d'ondes et le coefficient de destruction de glycine par photon incident et renvoie l'integrale du flux uv correspondant.
subroutine run
fait appel à toutes les fonctions qui vont representé le programme dans sa globalité.
real function uv_flux (longeur_onde)
Fonction qui renvoie pour une longeur d'onde donnée et une latitude fixée la valeur du flux UV.
real function aire (a, b)
Fonction qui integre le flux UV entre deux bornes de longueur d'onde.
subroutine calcul_tout
Créer un fichier .dat qui contient l'évolution du flux UV en fonction de la latitude.
real function uv_integrale (tet, lambda)
Renvoie l'integrale de flux UV avec en entrée une latitude et un intervalle de longeur d'ondes.
subroutine diminution_general (Fsources, aire_uv)
Prend en entrée une sources et une valeur de UV et donne en sortie un fichier decrivant la diminution des UV en fonction de la profondeur.
Public Attributes
real flux
real flux2
Detailed Description
Ce module contient toutes les méthodes qui font les traitements des données.
Author
LAHIYANE Atik
Definition at line 15 of file Controlleur.f90.
Member Function/Subroutine Documentation
real function controlleur::aire (real a, real b)
Fonction qui integre le flux UV entre deux bornes de longueur d'onde.
Author
LAHIYANE Atik
Parameters
[in] a,b
[out] aire
Definition at line 165 of file Controlleur.f90.
References uv_flux().
Referenced by uv_integrale().
subroutine controlleur::application_pert (character(len=20) name)
Demande à l'utilisateur d'entrée une latitude, un intervalle de longeur d'ondes et le coefficient de destruction de glycine par photon incident et renvoie l'integrale du flux uv correspondant.
Author
LAHIYANE Atik
Parameters
[in] name
[out] Fm : flux UV
Definition at line 75 of file Controlleur.f90.
References pertesuv::conversion_b(), pertesuv::showuvdestroyed(), and uv_integrale().
Referenced by bilan().
subroutine controlleur::bilan (character(len=20) name)
Fait le bilan (sources-pertes) en prenant comme paramètre d'entrée le nom de la molécule choisi par l'utilisateur.
Author
LAHIYANE Atik
Parameters
[in] name
Definition at line 36 of file Controlleur.f90.
References application_pert(), calcul_tout(), diminution_general(), and affichage::show().
Referenced by run().
subroutine controlleur::calcul_tout ()
Créer un fichier .dat qui contient l'évolution du flux UV en fonction de la latitude.
Author
LAHIYANE Atik
Parameters
[out] UV_vs_latitude.dat
Definition at line 193 of file Controlleur.f90.
References uv_integrale().
Referenced by bilan().
subroutine controlleur::diminution_general (real Fsources, real aire_uv)
Prend en entrée une sources et une valeur de UV et donne en sortie un fichier decrivant la diminution des UV en fonction de la profondeur.
Author
LAHIYANE Atik
Parameters
[out] uv_integrale
Definition at line 237 of file Controlleur.f90.
References readfromfile::diminution_uv_profondeur().
Referenced by bilan().
subroutine controlleur::run ()
fait appel à toutes les fonctions qui vont representé le programme dans sa globalité.
Author
LAHIYANE Atik il sera appelé depuis le "main" correspondant
Definition at line 108 of file Controlleur.f90.
References bilan(), readfromfile::filetoarray(), sources::research(), and sources::show_values().
Referenced by main().
real function controlleur::uv_flux (real longeur_onde)
Fonction qui renvoie pour une longeur d'onde donnée et une latitude fixée la valeur du flux UV.
Author
LAHIYANE Atik
Parameters
[in] longeur_onde
[out] Uv_flux
Definition at line 144 of file Controlleur.f90.
Referenced by aire().
real function controlleur::uv_integrale (integer tet, real, dimension(2) lambda)
Renvoie l'integrale de flux UV avec en entrée une latitude et un intervalle de longeur d'ondes.
Author
LAHIYANE Atik
Parameters
[out] uv_integrale
Definition at line 219 of file Controlleur.f90.
References aire(), and readfromfile::extraire_colonne().
Referenced by application_pert(), and calcul_tout().
Member Data Documentation
real controlleur::flux
Definition at line 21 of file Controlleur.f90.
real controlleur::flux2
Definition at line 22 of file Controlleur.f90.
The documentation for this module was generated from the following file:
Controlleur.f90